<?php

namespace Pluetzner\BlockBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EntityBlockRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EntityBlockRepository extends EntityRepository
{
}
