<?php

namespace Pluetzner\BlockBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Pluetzner\BlockBundle\Entity\EntityBlock;

/**
 * EntityBlockRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class EntityBlockRepository extends EntityRepository
{

    /**
     * @param string $slug
     * @param string $type
     * @return EntityBlock|null
     */
    public function findOneBySlugAndType($slug, $type){
        $qb = $this->createQueryBuilder('eb');

        $eb = $qb
            ->join('eb.entityBlockType', 'entityType')
            ->where('entityType.slug = :type')
            ->andWhere('eb.deleted = :deleted')
            ->andWhere('eb.slug = :slug')
            ->setParameters([
                'type' => $type,
                'slug' => $slug,
                'deleted' => false,
            ])
            ->getQuery()
            ->getOneOrNullResult();

        return $eb;
    }
}
