<?php

namespace Pluetzner\BlockBundle\Repository;

/**
 * ImageBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImportRepository extends \Doctrine\ORM\EntityRepository
{
}
