<?php

namespace Pluetzner\BlockBundle\Repository;

/**
 * StringBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OptionBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
