<?php

namespace Pluetzner\BlockBundle\Repository;

/**
 * TextBlockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextBlockRepository extends \Doctrine\ORM\EntityRepository
{
}
